# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d0239d1003ed3caabcd99891c4fc1ed85a0f97a3b38674d9cf6672e8e7b6c96affcea58f060e5ba4df762c7f8dfd68a1f8e8b9aa9d21f46054bc7292b72a3d

test:
  secret_key_base: 1d0f7f3b6d1db21924aba516839714b4e60c63d10b5eaae8f22c6058cc108f0076fc8a3177bf801056481db7feaed3303a335114c295275d3c0653e0416be08d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
